"""remove fixture data from fixture table

Revision ID: 5e3f6f4d16b2
Revises: 2afd0d5b6f80
Create Date: 2026-08-20 15:22:12.728394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e3f6f4d16b2'
down_revision: Union[str, Sequence[str], None] = '2afd0d5b6f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'fixture_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('fixture_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
